name: CI/CD Workflow

on:
  push:
    branches:
      - main # specify the branch you want to trigger the workflow on

jobs:
  build_and_test:
    runs-on: ubuntu-latest # specify the operating system for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # check out the repository code

    - name: Install Node.js
      uses: actions/setup-node@v2 # set up Node.js
      with:
        node-version: 14 # specify the Node.js version to use

    - name: Install Yarn
      run: yarn global add yarn # install Yarn globally using Yarn

    - name: Install Expo CLI
      run: yarn global add expo-cli # install Expo CLI globally using Yarn

    - name: Install EAS CLI
      run: yarn add @expo/eas-build-job # install EAS CLI using Yarn

    - name: Install dependencies
      run: yarn install # install dependencies using Yarn
      
    - name: Log in to Expo
      run: expo login -u chimiwangchukwangdi -p Expo_KKSBDW#586 # replace <USERNAME> and <PASSWORD> with your Expo account credentials

    - name: Build Android
      run: yarn eas build -p android

    - name: Build iOS
      run: yarn eas build -p ios
      
    - name: Run tests
      run: expo test # or any other command to run tests

  deploy:
    runs-on: ubuntu-latest # specify the operating system for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # check out the repository code

    - name: Install Node.js
      uses: actions/setup-node@v2 # set up Node.js
      with:
        node-version: 14 # specify the Node.js version to use

    - name: Install Yarn
      run: yarn global add yarn # install Yarn globally using Yarn

    - name: Install Expo CLI
      run: yarn global add expo-cli # install Expo CLI globally using Yarn

    - name: Install EAS CLI
      run: yarn global add eas-cli # install EAS CLI globally using Yarn

    - name: Install
      run: echo "This is the install step"

